//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string Grade { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public string StatusClass { get; set; }
        public string TeacherID { get; set; }
    }
}
