//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public string TypeExam { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    }
}
