//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int InfoID { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherPhoneNumber { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherPhoneNumber { get; set; }
    }
}
