version: '3'
volumes:
  mssql-data:
    driver: local
services:
  sql-server-be-358:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433
    # command: ["/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'yourStrong(!)Password' -i \"SchoolManagement.sql\""]
